[package]
name = "selene"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["tls", "admin"]
tls = []
admin = []

[dependencies]

[lints]
workspace = true
